### ISSUE TITLE
Fedora support and proper way to configure the plugin

### ISSUE THREAD

**Issue by dc740** [matveyt/neoclip#4]
I can select text, right click and use the neovim mouse menu to copy it (yes, in neovim, not part of the terminal emulator).
BUT for some reason using Y does not copy the code to the clipboard.

I have to add set clipboard=unnamedplus to my config to get the text into the clipboard. Is this expected? I found your plugin through a stackoverflow answer which suggested that should not be added to the config with this plugin.

Since you clearly have much more experience on this than me, do you know what could be causing this?

---
side note: I don't know if it was worth a full PR to add these.

Requirements for fedora 36

    sudo dnf install luajit-devel libX11-devel wayland-devel extra-cmake-modules

Vim-Plug install with trigger to compile after cloning (so you don't have to manually do anything else, as long as you have the installed the requirements before)

    Plug 'matveyt/neoclip', { 'do': 'cmake -S src -B build -G Ninja && ninja -C build install/strip' }

**Comment by matveyt** [comment]
1. The plugin gives possibility to access OS clipboard. It doesn't enforce it. Quite the opposite, a user is expected to make use of internal registers (`:h registers`) as much as possible. Therefore, setting `&clipboard` option is disadviced. Instead, one should prefix Normal mode commands with <kbd>"</kbd><kbd>+</kbd> manually (only) when needed.
2. Under `:h neoclip-build` I've put the requirements list for Debian. I don't feel there's a need to include such lists for all (major) Linux distros out there. It'll be enough if one can figure it out, as all such lists should look quite similar.
